# Fetching the latest node image on alpine linux
FROM node:alpine AS development

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /react-app

# Installing dependencies
COPY ./package.json /react-app
RUN npm install

# Copying all the files in our project
COPY . .

# Starting our application
CMD npm start

#PARA CREAR LA IMAGEN:  docker build -f dockerfile -t react .
#PARA CORRER EL CONTENEDOR: docker run -d -it -p 3000:3000  react